name: Build, Test, Deploy
on:
    push:

jobs:
    build:
        name: Build, Test
        # This job runs on Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

              # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                registry-url: 'https://registry.npmjs.org'

            - run: ./short-build.sh

            - name: artifact - npm tarball
              uses: actions/upload-artifact@v2
              with:
                  name: npm-tarball
                  path: nodejs/scripts/jsonix-logixboard-*.tgz

            - run: npm publish nodejs/scripts/jsonix-logixboard-*.tgz
              if: github.ref == 'refs/heads/master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
